package com.nuvio.app.features.player

import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier
import com.nuvio.app.features.settings.NuvioSubtitleSelectorStyle

@Composable
internal fun SubtitleModal(
    visible: Boolean,
    activeTab: SubtitleTab,
    selectorStyle: NuvioSubtitleSelectorStyle,
    subtitleTracks: List<SubtitleTrack>,
    selectedSubtitleIndex: Int,
    addonSubtitles: List<AddonSubtitle>,
    selectedAddonSubtitleId: String?,
    isLoadingAddonSubtitles: Boolean,
    preferredSubtitleLanguage: String,
    secondaryPreferredSubtitleLanguage: String?,
    subtitleStyle: SubtitleStyleState,
    subtitleDelayMs: Int,
    selectedAddonSubtitle: AddonSubtitle?,
    subtitleAutoSyncState: SubtitleAutoSyncUiState,
    onTabSelected: (SubtitleTab) -> Unit,
    subtitleSyncEnabled: Boolean,
    currentPlaybackPositionMs: Long,
    isPlaying: Boolean,
    onBuiltInTrackSelected: (Int) -> Unit,
    onAddonSubtitleSelected: (AddonSubtitle) -> Unit,
    onFetchAddonSubtitles: () -> Unit,
    onStyleChanged: ((SubtitleStyleState) -> SubtitleStyleState) -> Unit,
    onSubtitleDelayChanged: (Int) -> Unit,
    onSubtitleDelayReset: () -> Unit,
    onAutoSyncCapture: () -> Unit,
    onSyncByEarClick: () -> Unit,
    onAutoSyncCueSelected: (SubtitleSyncCue) -> Unit,
    onAutoSyncReload: () -> Unit,
    onTogglePlayback: () -> Unit,
    onDismiss: () -> Unit,
    modifier: Modifier = Modifier,
) {
    if (activeTab == SubtitleTab.Sync && selectorStyle == NuvioSubtitleSelectorStyle.Enhanced) {
        EnhancedSubtitleModal(
            visible = visible,
            activeTab = activeTab,
            subtitleTracks = subtitleTracks,
            selectedSubtitleIndex = selectedSubtitleIndex,
            addonSubtitles = addonSubtitles,
            selectedAddonSubtitleId = selectedAddonSubtitleId,
            isLoadingAddonSubtitles = isLoadingAddonSubtitles,
            subtitleStyle = subtitleStyle,
            subtitleDelayMs = subtitleDelayMs,
            selectedAddonSubtitle = selectedAddonSubtitle,
            subtitleAutoSyncState = subtitleAutoSyncState,
            onTabSelected = onTabSelected,
            subtitleSyncEnabled = subtitleSyncEnabled,
            currentPlaybackPositionMs = currentPlaybackPositionMs,
            isPlaying = isPlaying,
            onBuiltInTrackSelected = onBuiltInTrackSelected,
            onAddonSubtitleSelected = onAddonSubtitleSelected,
            onFetchAddonSubtitles = onFetchAddonSubtitles,
            onStyleChanged = onStyleChanged,
            onSubtitleDelayChanged = onSubtitleDelayChanged,
            onSubtitleDelayReset = onSubtitleDelayReset,
            onAutoSyncCapture = onAutoSyncCapture,
            onSyncByEarClick = onSyncByEarClick,
            onAutoSyncCueSelected = onAutoSyncCueSelected,
            onAutoSyncReload = onAutoSyncReload,
            onTogglePlayback = onTogglePlayback,
            onDismiss = onDismiss,
            modifier = modifier,
        )
        return
    }

    when (selectorStyle) {
        NuvioSubtitleSelectorStyle.Enhanced -> EnhancedSubtitleModal(
            visible = visible,
            activeTab = activeTab,
            subtitleTracks = subtitleTracks,
            selectedSubtitleIndex = selectedSubtitleIndex,
            addonSubtitles = addonSubtitles,
            selectedAddonSubtitleId = selectedAddonSubtitleId,
            isLoadingAddonSubtitles = isLoadingAddonSubtitles,
            subtitleStyle = subtitleStyle,
            subtitleDelayMs = subtitleDelayMs,
            selectedAddonSubtitle = selectedAddonSubtitle,
            subtitleAutoSyncState = subtitleAutoSyncState,
            onTabSelected = onTabSelected,
            subtitleSyncEnabled = subtitleSyncEnabled,
            currentPlaybackPositionMs = currentPlaybackPositionMs,
            isPlaying = isPlaying,
            onBuiltInTrackSelected = onBuiltInTrackSelected,
            onAddonSubtitleSelected = onAddonSubtitleSelected,
            onFetchAddonSubtitles = onFetchAddonSubtitles,
            onStyleChanged = onStyleChanged,
            onSubtitleDelayChanged = onSubtitleDelayChanged,
            onSubtitleDelayReset = onSubtitleDelayReset,
            onAutoSyncCapture = onAutoSyncCapture,
            onSyncByEarClick = onSyncByEarClick,
            onAutoSyncCueSelected = onAutoSyncCueSelected,
            onAutoSyncReload = onAutoSyncReload,
            onTogglePlayback = onTogglePlayback,
            onDismiss = onDismiss,
            modifier = modifier,
        )

        NuvioSubtitleSelectorStyle.Nuvio -> NuvioSubtitleModal(
            visible = visible,
            activeTab = activeTab,
            subtitleTracks = subtitleTracks,
            selectedSubtitleIndex = selectedSubtitleIndex,
            addonSubtitles = addonSubtitles,
            selectedAddonSubtitleId = selectedAddonSubtitleId,
            isLoadingAddonSubtitles = isLoadingAddonSubtitles,
            preferredSubtitleLanguage = preferredSubtitleLanguage,
            secondaryPreferredSubtitleLanguage = secondaryPreferredSubtitleLanguage,
            subtitleStyle = subtitleStyle,
            subtitleDelayMs = subtitleDelayMs,
            selectedAddonSubtitle = selectedAddonSubtitle,
            subtitleAutoSyncState = subtitleAutoSyncState,
            onBuiltInTrackSelected = onBuiltInTrackSelected,
            onAddonSubtitleSelected = onAddonSubtitleSelected,
            onFetchAddonSubtitles = onFetchAddonSubtitles,
            onStyleChanged = onStyleChanged,
            onSubtitleDelayChanged = onSubtitleDelayChanged,
            onSubtitleDelayReset = onSubtitleDelayReset,
            onAutoSyncCapture = onAutoSyncCapture,
            onAutoSyncCueSelected = onAutoSyncCueSelected,
            onAutoSyncReload = onAutoSyncReload,
            onTogglePlayback = onTogglePlayback,
            currentPlaybackPositionMs = currentPlaybackPositionMs,
            isPlaying = isPlaying,
            onDismiss = onDismiss,
            modifier = modifier,
        )
    }
}
